package com.gane.shoper.entity

data class VipCard(
      var birthday: String? = null,
      var cardvalue: Int = -1,
      var teltype: String? = null,
      var carddiscount: Int = -1,
      var own: String? = null,
      var coname: String? = null,
      var remark: String? = null,
      var auditdate: String? = null,
      var conssum: Int = -1,
      var saleremark: String? = null,
      var memberno: String? = null,
      var balance: Float = 0f,
      var totaladdvalues: Int = -1,
      var saledate: String? = null,
      var tel: String? = null,
      var cardtype: String? = null,
      var cardpasswd: String? = null,
      var state: Int = -1,
      var addr: String? = null,
      var issendmessage: String? = null,
      var email: String? = null,
      var cardlevel: String? = null,
      var begdate: String? = null,
      var saleman: String? = null,
      var sex: String? = null,
      var cardkind: String? = null,
      var postcode: String? = null,
      var transflag: Int = -1,
      var cardno: String? = null,
      var totalpoint: Int = -1,
      var constimes: String? = null,
      var oldcardno: String? = null,
      var pointscale: String? = null,
      var auditman: String? = null,
      var incardno: String? = null,
      var idcard: String? = null,
      var duty: String? = null,
      var totaladdtimes: Int = -1,
      var usemonth: Int = -1,
      var useful: String? = null
)